In [1]:
pip install pandas numpy matplotlib seaborn scikit-learn streamlit plotly

Requirement already satisfied: pandas in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.8.0)
Collecting streamlit
  Using cached streamlit-1.55.0-py3-none-any.whl.metadata (9.8 kB)
Collecting plotly
  Downloading plotly-6.6.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Using cached altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (1.9.0)
Collecting cachetools<8,>=5.5 (from streamlit)
  Using cached cachetools-7.0.4-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (8.3.0)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Using cached gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Collecting protobuf<7,>=3.20 (from streamlit)
  Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-23.0.1-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (6.5.3)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: jinja2 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached narwhals-2.17.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached streamlit-1.55.0-py3-none-any.whl (9.1 MB)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 367.6 kB/s eta 0:00:29
   - -------------------------------------- 0.5/11.0 MB 367.6 kB/s eta 0:00:29
   -- ------------------------------------- 0.8/11.0 MB 434.8 kB/s eta 0:00:24
   -- ------------------------------------- 0.8/11.0 MB 434.8 kB/s eta 0:00:24
   --- ------------------------------------ 1.0/11.0 MB 526.6 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/11.0 MB 600.4 kB/s eta 0:00:17
   ----- ---------------------------------- 1.6/11.0 MB 671.9 kB/s eta 0:00:15
   ------ --------------------------------- 1.8/11.0 MB 716.8 kB/s eta 0:00:13
   ------- -------------------------------- 2.1/11.0 MB 764.8 kB/s eta 0:00:12
   --------- ------------------------------ 2.6/11.0 MB 864.5 kB/s eta 0:00:10
   ---------- ----------------------------- 2.9/11.0 MB 913.0 kB/s eta 0:00:09
   ----------- ---------------------------- 3.1/11.0 MB 960.0 kB/s eta 0:00:09
   ------------- -------------------------- 3.7/11.0 MB 1.0 MB/s eta 0:00:08
   -------------- ------------------------- 3.9/11.0 MB 1.1 MB/s eta 0:00:07
   ---------------- ----------------------- 4.5/11.0 MB 1.1 MB/s eta 0:00:06
   ------------------ --------------------- 5.0/11.0 MB 1.2 MB/s eta 0:00:06
   ------------------- -------------------- 5.2/11.0 MB 1.2 MB/s eta 0:00:05
   -------------------- ------------------- 5.8/11.0 MB 1.3 MB/s eta 0:00:05
   ---------------------- ----------------- 6.3/11.0 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 6.8/11.0 MB 1.4 MB/s eta 0:00:04
   ------------------------- -------------- 7.1/11.0 MB 1.4 MB/s eta 0:00:03
   --------------------------- ------------ 7.6/11.0 MB 1.4 MB/s eta 0:00:03
   ---------------------------- ----------- 7.9/11.0 MB 1.4 MB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.5 MB/s eta 0:00:02
   -------------------------------- ------- 8.9/11.0 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.0 MB 1.5 MB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 1.5 MB/s  0:00:07
Using cached altair-6.0.0-py3-none-any.whl (795 kB)
Using cached cachetools-7.0.4-py3-none-any.whl (13 kB)
Using cached gitpython-3.1.46-py3-none-any.whl (208 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl (437 kB)
Using cached pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
Using cached smmap-5.0.3-py3-none-any.whl (24 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading plotly-6.6.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 2.6 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/9.9 MB 2.5 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.9 MB 2.6 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.9 MB 2.5 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.9 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.9 MB 2.6 MB/s eta 0:00:03
   -------------- ------------------------- 3.7/9.9 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 4.5/9.9 MB 2.7 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 2.7 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 2.8 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.9 MB 2.8 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 8.9/9.9 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 2.7 MB/s  0:00:03
Using cached narwhals-2.17.0-py3-none-any.whl (444 kB)
Downloading pyarrow-23.0.1-cp313-cp313-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.5 MB 3.7 MB/s eta 0:00:08
   -- ------------------------------------- 1.6/27.5 MB 3.7 MB/s eta 0:00:08
   --- ------------------------------------ 2.4/27.5 MB 3.8 MB/s eta 0:00:07
   ---- ----------------------------------- 3.1/27.5 MB 3.9 MB/s eta 0:00:07
   ----- ---------------------------------- 3.9/27.5 MB 4.0 MB/s eta 0:00:06
   ------- -------------------------------- 5.0/27.5 MB 4.0 MB/s eta 0:00:06
   -------- ------------------------------- 6.0/27.5 MB 4.2 MB/s eta 0:00:06
   --------- ------------------------------ 6.8/27.5 MB 4.2 MB/s eta 0:00:05
   ----------- ---------------------------- 7.6/27.5 MB 4.1 MB/s eta 0:00:05
   ------------ --------------------------- 8.7/27.5 MB 4.2 MB/s eta 0:00:05
   -------------- ------------------------- 10.0/27.5 MB 4.3 MB/s eta 0:00:05
   --------------- ------------------------ 11.0/27.5 MB 4.4 MB/s eta 0:00:04
   ----------------- ---------------------- 12.1/27.5 MB 4.5 MB/s eta 0:00:04
   ------------------- -------------------- 13.4/27.5 MB 4.6 MB/s eta 0:00:04
   -------------------- ------------------- 14.2/27.5 MB 4.6 MB/s eta 0:00:03
   --------------------- ------------------ 14.7/27.5 MB 4.5 MB/s eta 0:00:03
   ---------------------- ----------------- 15.5/27.5 MB 4.4 MB/s eta 0:00:03
   ----------------------- ---------------- 16.5/27.5 MB 4.4 MB/s eta 0:00:03
   ------------------------- -------------- 17.3/27.5 MB 4.3 MB/s eta 0:00:03
   ------------------------- -------------- 17.8/27.5 MB 4.3 MB/s eta 0:00:03
   --------------------------- ------------ 18.6/27.5 MB 4.3 MB/s eta 0:00:03
   ---------------------------- ----------- 19.4/27.5 MB 4.2 MB/s eta 0:00:02
   ---------------------------- ----------- 19.9/27.5 MB 4.2 MB/s eta 0:00:02
   ------------------------------ --------- 20.7/27.5 MB 4.1 MB/s eta 0:00:02
   ------------------------------ --------- 21.2/27.5 MB 4.1 MB/s eta 0:00:02
   ------------------------------- -------- 21.8/27.5 MB 4.0 MB/s eta 0:00:02
   ------------------------------- -------- 22.0/27.5 MB 4.0 MB/s eta 0:00:02
   -------------------------------- ------- 22.5/27.5 MB 3.9 MB/s eta 0:00:02
   --------------------------------- ------ 22.8/27.5 MB 3.9 MB/s eta 0:00:02
   --------------------------------- ------ 23.1/27.5 MB 3.7 MB/s eta 0:00:02
   --------------------------------- ------ 23.1/27.5 MB 3.7 MB/s eta 0:00:02
   --------------------------------- ------ 23.3/27.5 MB 3.6 MB/s eta 0:00:02
   ---------------------------------- ----- 23.6/27.5 MB 3.5 MB/s eta 0:00:02
   ---------------------------------- ----- 23.9/27.5 MB 3.4 MB/s eta 0:00:02
   ----------------------------------- ---- 24.1/27.5 MB 3.3 MB/s eta 0:00:02
   ----------------------------------- ---- 24.4/27.5 MB 3.3 MB/s eta 0:00:01
   ----------------------------------- ---- 24.6/27.5 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 24.9/27.5 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 25.2/27.5 MB 3.1 MB/s eta 0:00:01
   ------------------------------------ --- 25.2/27.5 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 25.7/27.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 25.7/27.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 26.0/27.5 MB 3.0 MB/s eta 0:00:01
   -------------------------------------- - 26.2/27.5 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 26.5/27.5 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 26.7/27.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.5 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.5 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 2.6 MB/s  0:00:10
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Installing collected packages: pytz, watchdog, toml, tenacity, smmap, pyarrow, protobuf, narwhals, cachetools, pydeck, plotly, pandas, gitdb, gitpython, altair, streamlit

   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   ----------------------------------------  0/16 [pytz]
   -- -------------------------------------  1/16 [watchdog]
   -- -------------------------------------  1/16 [watchdog]
   -- -------------------------------------  1/16 [watchdog]
   -- -------------------------------------  1/16 [watchdog]
   -- -------------------------------------  1/16 [watchdog]
   -- -------------------------------------  1/16 [watchdog]
   -- -------------------------------------  1/16 [watchdog]
   ----- ----------------------------------  2/16 [toml]
   ----- ----------------------------------  2/16 [toml]
   ------- --------------------------------  3/16 [tenacity]
   ------- --------------------------------  3/16 [tenacity]
   ------- --------------------------------  3/16 [tenacity]
   ---------- -----------------------------  4/16 [smmap]
   ---------- -----------------------------  4/16 [smmap]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]
   ------------ ---------------------------  5/16 [pyarrow]

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/sales_data.csv")

df.head()

         Date       Product     Category Region  Units  Revenue
0  2024-10-06  Coffee Maker         Home  North      9     3474
1  2024-03-23     Desk Lamp         Home   West      4     3332
2  2023-10-09         Shoes      Fashion  North      4     4636
3  2023-02-17       T-shirt      Fashion   East      1      362
4  2024-09-02        Laptop  Electronics  South      8     1680

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50000 non-null  object
 1   Product   50000 non-null  object
 2   Category  50000 non-null  object
 3   Region    50000 non-null  object
 4   Units     50000 non-null  int64
 5   Revenue   50000 non-null  int64
dtypes: int64(2), object(4)
memory usage: 2.3+ MB

              Units       Revenue
count  50000.000000  50000.000000
mean       5.493800   3348.166120
std        2.875616   2747.042324
min        1.000000     20.000000
25%        3.000000   1076.000000
50%        5.000000   2562.000000
75%        8.000000   5010.000000
max       10.000000  12000.000000

In [4]:
df.groupby("Category")["Revenue"].sum()

Category
Accessories    41080714
Electronics    42330442
Fashion        41882048
Home           42115102
Name: Revenue, dtype: int64

In [5]:
df.groupby("Region")["Revenue"].sum()

Region
East     41553745
North    42140366
South    41755407
West     41958788
Name: Revenue, dtype: int64

In [6]:
import pandas as pd

def load_data():

    df = pd.read_csv("data/raw/sales_data.csv")

    df["Date"] = pd.to_datetime(df["Date"])

    return df

In [7]:
def total_revenue(df):

    revenue = df["Revenue"].sum()

    return f"Total revenue generated: ${revenue:,.0f}"

In [8]:
def top_region(df):

    region = df.groupby("Region")["Revenue"].sum().idxmax()

    return f"Best performing region: {region}"

In [9]:
def top_product(df):

    product = df.groupby("Product")["Units"].sum().idxmax()

    return f"Most sold product: {product}"

In [10]:
def sales_trend(df):

    monthly = df.groupby(df["Date"].dt.to_period("M"))["Revenue"].sum()

    growth = monthly.pct_change().mean() * 100

    return f"Average monthly growth: {growth:.2f}%"

In [11]:
def generate_insights():

    df = load_data()

    insights = [

        total_revenue(df),
        top_category(df),
        top_region(df),
        top_product(df),
        sales_trend(df)

    ]

    return insights

In [12]:
from src.insight_engine import generate_insights

insights = generate_insights()

for i in insights:
    print(i)

ModuleNotFoundError: No module named 'src'